### ISSUE TITLE
Windows Phone 10

### ISSUE THREAD

**Issue by iNotDev** [MahdiGhiasi/XpoMusic#45]
How to compile this application under Windows Phone 10?

**Comment by marcoValkyriweb** [comment]
Have you tried downloading it from the Microsoft store? Under system requirements, ARM seems to be listed.

https://www.microsoft.com/store/productId/9N1N68MC7FXR

**Comment by iNotDev** [comment]
> 
> 
> Have you tried downloading it from the Microsoft store? Under system requirements, ARM seems to be listed.
> 
> https://www.microsoft.com/store/productId/9N1N68MC7FXR

The latest version of Windows 10 Phone is 10.0.15254.582
The minimum requirements from the store look like Windows 10 version 16299.0 or higher
